### ISSUE TITLE
mybatis-plus更新至3.4.3版本FgMybatisAutoConfiguration分页插件异常

### ISSUE THREAD

**Issue by sxrstrive** [FlyingGlass/backend-starter-mybatis#1]
近期对mybatis-plush升级至3.4.3版本，新版本的分页插件已由PaginationInterceptor调整为PaginationInnerInterceptor，再次使用该库版本时启动报异常，ClassNotFoundException

**Comment by flyingglass** [comment]
已经升级修复了，提交到maven central 使用1.0.1版本
